# Generated by Django 4.1.4 on 2023-12-17 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('Business_name', models.CharField(max_length=250)),
                ('Business_categrey', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('website', models.URLField()),
                ('specification', models.CharField(max_length=250)),
                ('heading', models.TextField()),
                ('about', models.TextField()),
                ('youtub', embed_video.fields.EmbedVideoField()),
                ('specification1', models.TextField()),
                ('specification2', models.TextField()),
                ('specification3', models.TextField()),
                ('specification4', models.TextField()),
                ('specification5', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('open_timing', models.CharField(max_length=250)),
                ('background_image', models.ImageField(upload_to='')),
                ('address_image', models.ImageField(upload_to='')),
                ('gallery_img1', models.ImageField(upload_to='listing')),
                ('gallery_img2', models.ImageField(upload_to='listing')),
                ('gallery_img3', models.ImageField(upload_to='listing')),
                ('gallery_img4', models.ImageField(upload_to='listing')),
                ('gallery_img5', models.ImageField(upload_to='listing')),
                ('keywords', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
