# Generated by Django 4.1.4 on 2023-12-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='listing',
            new_name='listings',
        ),
    ]
